EMAIL_CLICKS_QUERY = """
SELECT DISTINCT url
FROM PC_FIVETRAN_DB.DBT_BADDISON_NEWSLETTER_EMAILS.NEWSLETTER_CLICKS
WHERE click_type = 'item_click'
AND click_ts >= '2022-11-16'
AND url NOT IN (SELECT DISTINCT url FROM PC_FIVETRAN_DB.STAGING.NEWSLETTER_ONELINKS_QUERY_PARAMS)
"""

EMAIL_CLICKS_COLS = ['url']

ONELINKS_QUERY = """
SELECT *
FROM PC_FIVETRAN_DB.STAGING.NEWSLETTER_ONELINKS_QUERY_PARAMS

"""

ONELINKS_QUERY_COLS = [
    'URL',
    'C',
    'AF_DP',
    'AF_ADSET',
    'sectionNumber',
    'sectionName',
    'PID',
    'DOMAIN',
    'PARSED_ONELINK',
    'UTM_MEDIUM',
    'UTM_CAMPAIGN',
    'UTM_CONTENT'
]